gui:
  theme:
    selectedLineBgColor:
      - underline
      # selectedRangeBgColor:
      #   - underline
  nerdFontsVersion: "3"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
services:
  'gitlab.dwellerlab.com': 'gitlab:gitlab.dwellerlab.com'
os:
  editPreset: 'nvim-remote' #https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#configuring-file-editing
customCommands:
  - key: <c-r>
    description: AI commit
    context: "files"
    command: 'commit-gen > .git/COMMIT_EDITMSG && cat .git/COMMIT_EDITMSG && ${EDITOR} .git/COMMIT_EDITMSG && [ -s .git/COMMIT_EDITMSG ] && git commit -F .git/COMMIT_EDITMSG || echo "Commit message is empty, commit aborted."'
    loadingText: "Generating Commit"
    output: terminal
